### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by zameschua** [zameschua/custom-link#1]
### Client
- [ ] Make front-end tell the user when the link is successfully created. 2 options: View the link OR create another link
- [ ] Add Api doc
- [ ] Clean up the ugly ass code
- [ ] Let users know that links will be there for 30 days

### Server
- [ ] Fix the existing bug
- [ ] Format HTTP response properly
- [ ] Re-organise backend code to fit MVC architecture
- [ ] Implement 30-day link (Store linked list in DB?)
- [ ] Record down the number of accesses per link, and the access location / ip?

### Future
- [ ] Host the website on AWS
- [ ] Install Docker?
- [ ] Let users create account for permanent links
    - [ ] Create account
    - [ ] Generate API keys
    - [ ] Split DB to `link` and `users`, and need to mark which links are permanent
- [ ] Dashboard to see how many clicks
